import {Poppins } from "next/font/google";
import "./globals.css";

import NextThemeProvider from "@/provider/NextThemeProvider";



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400" , "500" , "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <NextThemeProvider>{children}</NextThemeProvider>
      </body>
    </html>
  );
}
